version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: nakama-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: localdb
      POSTGRES_DB: nakama
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nakama:
    image: heroiclabs/nakama:latest
    container_name: nakama
    depends_on:
      - postgres
    ports:
      - "7350:7350"
      - "7351:7351"
    volumes:
      # 🔥 IMPORTANT: USE ABSOLUTE PATH (Windows fix)
      - C:/Users/vedan/Desktop/nakamaproject/nakama/modules:/nakama/data/modules
    entrypoint:
      - /bin/sh
      - -ecx
      - |
        sleep 10
        /nakama/nakama \
        --database.address postgres://root:localdb@postgres:5432/nakama \
        --console.username admin \
        --console.password admin \
        --socket.server_key supersecret \
        --session.encryption_key supersecret1 \
        --session.refresh_encryption_key supersecret2 \
        --runtime.http_key supersecret \
        --runtime.js_entrypoint main.js \
        --logger.level debug

volumes:
  postgres_data: